# Generated by Django 6.0.1 on 2026-04-29 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE login_userprofile ADD COLUMN created_by_id INTEGER REFERENCES auth_user(id) ON DELETE SET NULL;",
            "ALTER TABLE login_userprofile DROP COLUMN created_by_id;",
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='created_by',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
                ),
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE login_userprofile ADD COLUMN password_display VARCHAR(255);",
            "ALTER TABLE login_userprofile DROP COLUMN password_display;",
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='password_display',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
            ]
        ),
    ]


