# Generated by Django 6.0.1 on 2026-04-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_enquiry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='created_by',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
