# Generated by Django 6.0.1 on 2026-05-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_enquiry_fare_type_enquiry_pnr_enquiry_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='label_colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
