# Generated by Django 6.0.1 on 2026-05-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_enquiry_label_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='label_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
