# Generated by Django 6.0.1 on 2026-05-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_enquiry_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='label_colour',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='label_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
