# Generated by Django 6.0.1 on 2026-05-06 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_alter_enquiry_travel_date_to_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_no', models.CharField(max_length=100, unique=True)),
                ('passport_number', models.CharField(max_length=100)),
                ('passport_detail', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('visa_number', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_date', models.DateField(blank=True, null=True)),
                ('mofa_number', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_post_date', models.DateField(blank=True, null=True)),
                ('passport_return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visa',
                'ordering': ['-created_at'],
            },
        ),
    ]
