# Generated by Django 6.0.1 on 2026-05-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='fill_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
