# Generated by Django 6.0.1 on 2026-05-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_alter_visa_contact_no_alter_visa_fill_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='fill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
